apiVersion: 1

datasources:
  - name: sshame-influxdb
    type: influxdb
    access: proxy
    orgId: 1
    isDefault: true
    editable: true
    url: http://sshame-influxdb:8086
    jsonData:
      version: Flux
      organization: sshame
      defaultBucket: sshame
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}