{
 "title": "sshame-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Failed attempts",
   "type": "timeseries",
   "description": "This visualization shows the total amount of failed SSH attempts per timeframe",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  $__timeGroup(ts, '1m') AS time,\r\n  COUNT(*) AS value\r\nFROM ssh_events\r\nWHERE $__timeFilter(ts)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "geomap",
   "description": "This dashboard uses the IP2Location LITE database for IP geolocation (https://lite.ip2location.com)",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  ts            AS time,\r\n  lat           AS latitude,\r\n  lon           AS longitude,\r\n  ip,\r\n  username,\r\n  country,\r\n  port,\r\n  1             AS value\r\nFROM ssh_events\r\nWHERE $__timeFilter(ts)\r\n  AND lat IS NOT NULL AND lon IS NOT NULL;\r\n"
    }
   ]
  },
  {
   "title": "Username distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the used user names from failed SSH attempts in the selected timeframe",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  username AS metric,\r\n  COUNT(*) AS value\r\nFROM ssh_events\r\nWHERE $__timeFilter(ts)\r\nGROUP BY username\r\nORDER BY value DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "IP distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the used IPs from failed SSH attempts in the selected timeframe",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  ip AS metric,\r\n  COUNT(*) AS value\r\nFROM ssh_events\r\nWHERE $__timeFilter(ts)\r\nGROUP BY ip\r\nORDER BY value DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Port distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the used ports from failed SSH attempts in the selected timeframe",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  port AS port,\r\n  COUNT(*) AS value\r\nFROM ssh_events\r\nWHERE $__timeFilter(ts)\r\nGROUP BY port\r\nORDER BY value DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Country distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the country from which a failed SSH attempt in the selected timeframe originated",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  country AS metric,\r\n  COUNT(*) AS value\r\nFROM ssh_events\r\nWHERE country IS NOT NULL\r\n  AND country <> ''\r\nGROUP BY country\r\nORDER BY value DESC\r\nLIMIT 100;\r\n"
    }
   ]
  }
 ]
}