version: '3.8'
services:
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  backend:
    build: ./backend
    volumes:
      - /var/log/auth.log:/hostlog/auth.log:ro
    depends_on:
      - influxdb

volumes:
  influx-data:
  grafana-storage:
