{
 "title": "sshame-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Failed attempts",
   "type": "timeseries",
   "description": "This visualization shows the total amount of failed SSH attempts per timeframe",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sshame\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ssh_fail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\r\n  |> group(columns: [])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)\r\n  |> yield(name: \"failed_attempts\")\r\n"
    }
   ]
  },
  {
   "title": "IP distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the used IPs from failed SSH attempts in the selected timeframe",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sshame\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ssh_fail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\r\n  |> group(columns: [\"ip\"])\r\n  |> count()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 10)\r\n  |> map(fn: (r) => ({ r with \" \": r._value }))\r\n  |> keep(columns: [\"ip\", \" \"])\r\n"
    }
   ]
  },
  {
   "title": "Username distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the used user names from failed SSH attempts in the selected timeframe",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sshame\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ssh_fail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\r\n  |> group(columns: [\"user\"])\r\n  |> count()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 10)\r\n  |> map(fn: (r) => ({ r with \" \": r._value }))\r\n  |> keep(columns: [\"user\", \" \"])\r\n"
    }
   ]
  },
  {
   "title": "Country distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the country from which a failed SSH attempt in the selected timeframe originated",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sshame\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ssh_fail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\r\n  |> group(columns: [\"country\"])\r\n  |> filter(fn: (r) => r.country != \"Unknown\")\r\n  |> count()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 10)\r\n  |> map(fn: (r) => ({ r with \" \": r._value }))\r\n  |> keep(columns: [\"country\", \" \"])\r\n"
    }
   ]
  },
  {
   "title": "Port distribution",
   "type": "piechart",
   "description": "This chart shows the distribution of the used ports from failed SSH attempts in the selected timeframe",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sshame\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ssh_fail\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\r\n  |> group(columns: [\"port\"])\r\n  |> count()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: 10)\r\n  |> map(fn: (r) => ({ r with \" \": r._value }))\r\n  |> keep(columns: [\"port\", \" \"])\r\n"
    }
   ]
  }
 ]
}